# Generated by Django 3.1.2 on 2021-01-26 20:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdvalue',
            name='check_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 20, 5, 13, 762609, tzinfo=utc), verbose_name='Дата снятия показания'),
        ),
    ]
