# Generated by Django 3.1.2 on 2021-01-26 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastorage', '0002_auto_20210126_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdvalue',
            name='check_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата снятия показания'),
        ),
    ]
